services:
  onyx:
    image: onyx:0.0.1
    ports:
      - "8014:8080"
    restart: unless-stopped
    environment:
      - ONYX_MARKDOWN_DIRECTORY=testdata
    volumes:
      - ./testdata:/app/testdata
